#!/bin/bash
echo ""
echo "***********************************************"
echo "*  Good on you for backing up your files! :D  *"
echo "***********************************************"
echo ""
rsync -rvvu --exclude={'Music/Apple Music'} /mnt/Media/ /mnt/backup/
echo ""
echo "***********************************************************"
echo "*  Your sensitive data is now safe from catastrophe. :)   *"
echo "***********************************************************"
echo ""
