#!/bin/bash
echo ""
echo "***********************************************"
echo "*  Good on you for backing up your files! :D  *"
echo "***********************************************"
echo ""
rsync -rvvu --delete --exclude={'Desktop','Downloads','Documents','Personal Programs','Coding-Projects'} --delete-excluded /mnt/Entertainment/Libraries /mnt/backup
echo ""
echo "***********************************************************"
echo "*  Your sensitive data is now safe from catastrophe. :)   *"
echo "***********************************************************"
echo ""
